### ISSUE TITLE
Grafana Agent Subordinate Errors out for non-leader units

### ISSUE THREAD

**Issue by deusebio** [canonical/grafana-agent-k8s-operator#140]
### Bug Description

I'm deploying Kafka (on VMs) with multiple units (n=3). When I deploy and relate the grafana agent charm, the grafana-agent unit related to the Kafka juju leader unit works fine but the other two (related to the non-leaders units) errors out because of a permission error in the relation data bag. 

This is the output of the juju status

```
Model    Controller  Cloud/Region         Version  SLA          Timestamp
default  dev         localhost/localhost  2.9.42   unsupported  23:14:08Z

App            Version  Status  Scale  Charm          Channel  Rev  Exposed  Message
grafana-agent           active      3  grafana-agent  edge       2  no       
kafka                   active      3  kafka          edge     106  no       
zookeeper               active      3  zookeeper      edge      92  no       

Unit                Workload  Agent  Machine  Public address  Ports  Message
kafka/6*            active    idle   24       10.21.168.7            
  grafana-agent/2   active    idle            10.21.168.7            
kafka/7             error     idle   25       10.21.168.75           hook failed: "cos-agent-relation-joined"
  grafana-agent/0*  active    idle            10.21.168.75           
kafka/8             error     idle   26       10.21.168.72           hook failed: "cos-agent-relation-joined"
  grafana-agent/1   active    idle            10.21.168.72           
zookeeper/6         active    idle   27       10.21.168.30           
zookeeper/7*        active    idle   28       10.21.168.101          
zookeeper/8         active    idle   29       10.21.168.85           
```

### To Reproduce

1. juju deploy kafka -n3 --channel edge
2. juju deploy zookeeper -n3 --channel edge
3. juju relate kafka zookeeper
4. juju deploy grafana-agent --channel edge
5. (wait everything to be active)
6. juju relate grafana-agent kafka

### Environment

juju version 
2.9.42-ubuntu-amd64

lxd version 
5.11

### Relevant log output

```shell
unit-kafka-8: 23:13:51 ERROR unit.kafka/8.juju-log cos-agent:27: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kafka-8/charm/./src/charm.py", line 503, in <module>
    main(KafkaCharm)
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-kafka-8/charm/lib/charms/grafana_agent/v0/cos_agent.py", line 251, in _on_refresh
    relation.data[self._charm.app].update({"config": self._generate_databag_content()})
  File "/usr/lib/python3.10/_collections_abc.py", line 994, in update
    self[key] = other[key]
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/model.py", line 1473, in __setitem__
    self._validate_write(key, value)
  File "/var/lib/juju/agents/unit-kafka-8/charm/venv/ops/model.py", line 1459, in _validate_write
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: kafka/8 is not leader and cannot write application data.
unit-kafka-8: 23:13:51 ERROR juju.worker.uniter.operation hook "cos-agent-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by rbarry82** [comment]
Closed by #142
