### ISSUE TITLE
(machine) Exception raised on teardown: `juju_topology.InvalidUUIDError: 'None' is not a valid UUID`

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-k8s-operator#176]
### Bug Description

During a CI itest teardown, the charm [raised an exception](https://github.com/canonical/cos-lite-bundle/actions/runs/4750259788/jobs/8438274005#step:9:1611).
Perhaps it's because the removal was forceful.

### To Reproduce

juju remove-application.

### Environment

```
Model                    Controller           Cloud/Region         Version  SLA          Timestamp
test-machine-agent-bnmx  github-pr-506db-lxd  localhost/localhost  3.1.2    unsupported  04:47:54Z

SAAS        Status  Store  URL
grafana     active  local  admin/test-machine-agent-bnmx.grafana-dashboards
loki        active  local  admin/test-machine-agent-bnmx.loki-logging
prometheus  active  local  admin/test-machine-agent-bnmx.prometheus-receive-remote-write

App                  Version  Status  Scale  Charm          Channel        Rev  Exposed  Message
agent                         active      4  grafana-agent  edge             7  no       
principal-cos-agent           active      2  zookeeper      edge            97  no       
principal-juju-info  22.04    active      2  ubuntu         latest/stable   22  no       

```

### Relevant log output

```shell
unit-agent-3: 03:55:30 ERROR unit.unit-agent-3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-agent-3/charm/./src/charm.py", line 473, in <module>
    main(GrafanaAgentMachineCharm)
  File "/var/lib/juju/agents/unit-agent-3/charm/venv/ops/main.py", line 429, in main
    charm = charm_class(framework)
  File "/var/lib/juju/agents/unit-agent-3/charm/./src/charm.py", line 161, in __init__
    super().__init__(*args)
  File "/var/lib/juju/agents/unit-agent-3/charm/src/grafana_agent.py", line 108, in __init__
    self._remote_write = PrometheusRemoteWriteConsumer(
  File "/var/lib/juju/agents/unit-agent-3/charm/lib/charms/prometheus_k8s/v0/prometheus_remote_write.py", line 641, in __init__
    self.topology = JujuTopology.from_charm(charm)
  File "/var/lib/juju/agents/unit-agent-3/charm/lib/charms/observability_libs/v0/juju_topology.py", line 154, in from_charm
    return cls(
  File "/var/lib/juju/agents/unit-agent-3/charm/lib/charms/observability_libs/v0/juju_topology.py", line 123, in __init__
    raise InvalidUUIDError(model_uuid)
charms.observability_libs.v0.juju_topology.InvalidUUIDError: 'None' is not a valid UUID.
```

**Comment by Abuelodelanada** [comment]
Hi @sed-i 

With this deploy:

![image](https://github.com/canonical/grafana-agent-k8s-operator/assets/939888/77f3367a-b9f1-4945-99e7-4ed8d00fd1cf)

related to this COS-Lite:

![image](https://github.com/canonical/grafana-agent-k8s-operator/assets/939888/34d61bf7-d385-492b-a554-5ab6a9b0c48f)


And after removing the application:

```shell
╭─ubuntu@charm-dev-juju-31 ~/repos/grafana-agent-k8s-operator ‹too_many_relations› [lxd:apps]
╰─$ juju remove-application grafana-agent --force --no-wait --destroy-storage
will remove application grafana-agent
- will remove unit grafana-agent/1
```

I see no errors in the log:

```log
machine-0: 19:27:48.022 INFO juju.worker.deployer checking unit "grafana-agent/1"
machine-0: 19:27:49.628 INFO juju.worker.deployer checking unit "grafana-agent/1"
machine-0: 19:27:49.648 INFO juju.worker.deployer recalling unit "grafana-agent/1"
unit-grafana-agent-1: 19:27:49.652 INFO juju.worker.logger logger worker stopped
unit-zookeeper-0: 19:27:50.292 INFO juju.worker.uniter.operation ran "cos-agent-relation-departed" hook (via hook dispatching script: dispatch)
machine-0: 19:27:50.432 INFO juju.worker.deployer removing unit "grafana-agent/1"
machine-0: 19:27:50.443 ERROR juju.worker.dependency "deployer" manifold worker returned unexpected error: permission denied
machine-0: 19:27:53.549 INFO juju.worker.deployer new context: units "zookeeper/0", stopped ""
machine-0: 19:27:53.559 INFO juju.worker.deployer creating new agent config for "zookeeper/0"
machine-0: 19:27:53.571 INFO juju.worker.deployer starting workers for "zookeeper/0"
machine-0: 19:27:53.588 INFO juju.worker.deployer checking unit "zookeeper/0"
machine-0: 19:27:53.635 INFO juju.worker.deployer checking unit "zookeeper/0"
machine-0: 19:27:53.667 INFO juju.api connection established to "wss://10.240.106.146:17070/model/01f51b82-f93b-42a4-8c7b-83e6f4dac000/api"
unit-zookeeper-0: 19:27:53.572 INFO juju Starting unit workers for "zookeeper/0"
unit-zookeeper-0: 19:27:53.683 INFO juju.worker.apicaller [01f51b] "unit-zookeeper-0" successfully connected to "10.240.106.146:17070"
unit-zookeeper-0: 19:27:53.769 INFO juju.worker.migrationminion migration phase is now: NONE
unit-zookeeper-0: 19:27:53.771 INFO juju.worker.logger logger worker started
unit-zookeeper-0: 19:27:53.803 INFO juju.worker.upgrader no waiter, upgrader is done
machine-0: 19:27:53.837 INFO juju.worker.leadership zookeeper/0 promoted to leadership of zookeeper
machine-0: 19:27:53.908 INFO juju.agent.tools ensure jujuc symlinks in /var/lib/juju/tools/unit-zookeeper-0
machine-0: 19:27:53.908 INFO juju.agent.tools was a symlink, now looking at /var/lib/juju/tools/3.1.2-ubuntu-amd64
unit-zookeeper-0: 19:27:54.130 INFO juju.worker.uniter unit "zookeeper/0" started
unit-zookeeper-0: 19:27:54.165 INFO juju.worker.uniter hooks are retried true
```

Are you able to reproduce it now?
