### ISSUE TITLE
Wrong promtail binary in grafana-agent-k8s rev 75:  /bin/agent: exec format error

### ISSUE THREAD

**Issue by taurus-forever** [canonical/grafana-agent-k8s-operator#299]
### Bug Description

Deploying grafana-agent-k8s on ARM throuw an error in debug-log: ERROR cannot start service: fork/exec /bin/agent: exec format error.

I suspect AMD version is released for ARM.

### To Reproduce

juju set-model-constraints arch=arm64
juju deploy postgresql-k8s --trust --channel 14/edge --config profile=testing # rev248
juju deploy grafana-agent-k8s --trust --channel edge # rev75
... relate all together with COS.

### Environment

juju 3.4.2

```
App                  Version  Status   Scale  Charm                Channel        Rev  Address        Exposed  Message
grafana-agent-k8s             active       1  grafana-agent-k8s    latest/edge     75  10.43.218.46   no       
postgresql-k8s       14.11    waiting      1  postgresql-k8s       14/candidate   248  10.43.110.157  no       installing agent
```

### Relevant log output

```shell
unit-grafana-agent-k8s-0: 10:29:21 ERROR juju.worker.uniter.operation hook "agent-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-grafana-agent-k8s-0: 10:29:21 ERROR juju.worker.uniter pebble poll failed for container "agent": failed to send pebble-ready event: hook failed
unit-grafana-agent-k8s-0: 10:29:25 ERROR unit.grafana-agent-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/./src/charm.py", line 261, in <module>
    main(GrafanaAgentK8sCharm)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/./src/charm.py", line 127, in _on_agent_pebble_ready
    self._container.autostart()
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/model.py", line 2149, in autostart
    self._pebble.autostart_services()
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/pebble.py", line 1899, in autostart_services
    return self._services_action('autostart', [], timeout, delay)
  File "/var/lib/juju/agents/unit-grafana-agent-k8s-0/charm/venv/ops/pebble.py", line 2001, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "agent" (cannot start service: fork/exec /bin/agent: exec format error)
----- Logs from task 0 -----
2024-05-07T08:29:25Z ERROR cannot start service: fork/exec /bin/agent: exec format error
-----
```

**Comment by simskij** [comment]
Resolved. Discussed with Alex in person.
